import Link from "next/link";
import { notFound } from "next/navigation";
import InternalEventActions from "@/components/InternalEventActions";
import { createAuthenticatedSupabaseClient } from "@/lib/supabase-auth.server";
import { requireRole } from "@/lib/require-role.server";
import { ROLES } from "@/lib/roles";
export const dynamic = "force-dynamic";
export default async function InternalEventPage({ params }: { params: Promise<{ id: string }> }) { const profile = await requireRole([ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.ARTISTIC_DIRECTOR]); const { id } = await params; const supabase = await createAuthenticatedSupabaseClient(); const { data: event } = await supabase.from("internal_events").select("*, creator:profiles!internal_events_created_by_fkey(nom,full_name)").eq("id", id).maybeSingle(); if (!event) notFound(); const creator = Array.isArray(event.creator) ? event.creator[0] : event.creator; const canManage = event.created_by === profile.id || [ROLES.SUPER_ADMIN, ROLES.ADMIN].includes(profile.role as any); return <main className="min-h-screen bg-black px-5 py-8 text-white md:px-10"><div className="mx-auto max-w-4xl"><Link href="/evenements" className="text-sm text-zinc-500">← Événements LMG</Link><section className="mt-7 rounded-[28px] border border-zinc-800 bg-zinc-950 p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-yellow-500">{event.type}</p><h1 className="mt-4 text-4xl font-black">{event.titre}</h1></div><span className="rounded-full border border-zinc-800 px-3 py-1 text-xs text-zinc-400">{event.statut}</span></div><p className="mt-3 text-zinc-500">Créé par {creator?.nom || creator?.full_name || "LMG"}</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><Info label="Début" value={formatDate(event.date_debut)} /><Info label="Fin" value={event.date_fin ? formatDate(event.date_fin) : "Non définie"} /><Info label="Lieu" value={event.lieu || "Non défini"} /><Info label="Rappel" value={formatReminder(event.reminder_minutes)} /></div>{event.description && <p className="mt-7 whitespace-pre-wrap border-t border-zinc-800 pt-7 leading-7 text-zinc-400">{event.description}</p>}{event.lien_visio && <a href={event.lien_visio} target="_blank" rel="noreferrer" className="mt-6 inline-block rounded-xl bg-white px-5 py-3 font-bold text-black">Rejoindre la visioconférence</a>}{canManage && <InternalEventActions id={event.id} title={event.titre} participantIds={event.participant_ids || []} />}</section></div></main>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-black p-5"><p className="text-xs text-zinc-600">{label}</p><p className="mt-2 font-bold">{value}</p></div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("fr-FR", { dateStyle: "long", timeStyle: "short" }).format(new Date(value)); }
function formatReminder(value: number) { if (!value) return "Aucun"; if (value === 1440) return "1 jour avant"; if (value >= 60) return `${value / 60} heure${value > 60 ? "s" : ""} avant`; return `${value} minutes avant`; }
