"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type Campaign = { id: string; titre: string | null; statut: string | null; budget: number | string | null; objectif: string | null; date_debut: string | null; date_fin: string | null; artistes: { nom?: string | null } | null; projets: { titre?: string | null } | null };

function euro(value: Campaign["budget"]) { return `${Number(value || 0).toLocaleString("fr-FR", { maximumFractionDigits: 0 })} €`; }
function date(value: string | null) { return value ? new Intl.DateTimeFormat("fr-FR", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "À définir"; }
const statusStyle: Record<string, string> = { "En cours": "border-emerald-500/30 bg-emerald-500/10 text-emerald-300", "En préparation": "border-blue-500/30 bg-blue-500/10 text-blue-300", "En pause": "border-amber-500/30 bg-amber-500/10 text-amber-300", Terminée: "border-zinc-700 bg-zinc-900 text-zinc-400", Annulée: "border-red-500/30 bg-red-500/10 text-red-300" };

export default function CampaignPortfolio({ campaigns, publications, audience }: { campaigns: Campaign[]; publications: number; audience: number }) {
  const [search, setSearch] = useState(""); const [filter, setFilter] = useState("Actives");
  const active = campaigns.filter((campaign) => !["Terminée", "Annulée"].includes(campaign.statut || "")).length;
  const budget = campaigns.reduce((sum, campaign) => sum + Number(campaign.budget || 0), 0);
  const visible = useMemo(() => { const query = search.trim().toLowerCase(); return campaigns.filter((campaign) => { const state = filter === "Toutes" || filter === "Actives" && !["Terminée", "Annulée"].includes(campaign.statut || "") || campaign.statut === filter; return state && (!query || [campaign.titre, campaign.objectif, campaign.statut, campaign.artistes?.nom, campaign.projets?.titre].some((value) => value?.toLowerCase().includes(query))); }); }, [campaigns, filter, search]);
  return <>
    <section className="mb-8 grid grid-cols-2 gap-3 xl:grid-cols-4">{[{ label: "Campagnes actives", value: active, detail: `${campaigns.length} au total` }, { label: "Budget engagé", value: euro(budget), detail: "toutes campagnes" }, { label: "Publications", value: publications, detail: "médias & influence" }, { label: "Audience potentielle", value: audience.toLocaleString("fr-FR"), detail: "portée influence" }].map((stat) => <div key={stat.label} className="rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-zinc-600">{stat.label}</p><p className="mt-3 text-2xl font-bold sm:text-3xl">{stat.value}</p><p className="mt-1 text-xs text-zinc-700">{stat.detail}</p></div>)}</section>
    <section className="overflow-hidden rounded-3xl border border-zinc-800 bg-zinc-950"><div className="border-b border-zinc-800 p-5 sm:p-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><h2 className="text-xl font-bold">Portefeuille marketing</h2><p className="mt-1 text-sm text-zinc-600">{visible.length} campagne{visible.length > 1 ? "s" : ""}</p></div><div className="flex gap-1 overflow-x-auto rounded-xl border border-zinc-800 bg-black p-1">{["Actives", "En préparation", "En cours", "En pause", "Terminée", "Toutes"].map((item) => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-lg px-3 py-2.5 text-xs font-semibold ${filter === item ? "bg-white text-black" : "text-zinc-500 hover:text-white"}`}>{item}</button>)}</div></div><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Rechercher une campagne, un artiste ou un projet…" className="mt-5 w-full rounded-xl border border-zinc-800 bg-black px-4 py-3 text-sm outline-none placeholder:text-zinc-700 focus:border-zinc-500" /></div>
      {visible.length === 0 ? <div className="px-6 py-20 text-center"><p className="text-lg font-semibold">Aucune campagne trouvée</p><button onClick={() => { setFilter("Toutes"); setSearch(""); }} className="mt-5 rounded-xl border border-zinc-700 px-4 py-2.5 text-sm font-semibold">Tout afficher</button></div> : <div className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-3">{visible.map((campaign) => <Link key={campaign.id} href={`/campagnes/${campaign.id}`} className="group flex min-h-64 flex-col rounded-2xl border border-zinc-800 bg-black p-5 hover:border-zinc-600"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-xs font-semibold uppercase tracking-wider text-zinc-600">{campaign.artistes?.nom || "Campagne LMG"}</p><h3 className="mt-2 truncate text-xl font-bold">{campaign.titre || "Sans titre"}</h3></div><span className={`shrink-0 rounded-lg border px-2.5 py-1.5 text-[10px] font-bold ${statusStyle[campaign.statut || ""] || "border-zinc-700 text-zinc-400"}`}>{campaign.statut || "À préparer"}</span></div><p className="mt-4 line-clamp-2 text-sm leading-6 text-zinc-500">{campaign.objectif || "Objectif à préciser"}</p><div className="mt-auto pt-6"><div className="flex items-center justify-between border-t border-zinc-900 pt-4"><div><p className="text-xs text-zinc-700">{date(campaign.date_debut)} → {date(campaign.date_fin)}</p><p className="mt-1 truncate text-xs text-zinc-600">{campaign.projets?.titre || "Sans projet lié"}</p></div><span className="text-sm font-bold">{euro(campaign.budget)}</span></div></div></Link>)}</div>}
    </section>
  </>;
}
