"use client";

import Link from "next/link";
import { useState } from "react";
import { supabaseBrowser } from "@/lib/supabase-browser";

type Props = { project: any; tasks: any[]; milestones: any[]; resources: any[]; updates: any[]; members: any[]; profiles: any[] };
const tabs = ["Vue d’ensemble", "Cadrage", "Exécution", "Ressources", "Journal"] as const;

export default function InternalProjectWorkspace(props: Props) {
  const { project, tasks, profiles } = props;
  const [tab, setTab] = useState<(typeof tabs)[number]>("Vue d’ensemble");
  const [milestones, setMilestones] = useState(props.milestones);
  const [resources, setResources] = useState(props.resources);
  const [updates, setUpdates] = useState(props.updates);
  const [members, setMembers] = useState(props.members);
  const [milestoneTitle, setMilestoneTitle] = useState("");
  const [milestoneDate, setMilestoneDate] = useState("");
  const [resourceName, setResourceName] = useState("");
  const [resourceUrl, setResourceUrl] = useState("");
  const [updateText, setUpdateText] = useState("");
  const [updateType, setUpdateType] = useState("Mise à jour");
  const [memberId, setMemberId] = useState("");
  const [memberRole, setMemberRole] = useState("Contributeur");

  async function addMilestone(e: React.FormEvent) { e.preventDefault(); const { data, error } = await supabaseBrowser.from("internal_project_milestones").insert({ project_id: project.id, titre: milestoneTitle.trim(), deadline: milestoneDate || null }).select("*").single(); if (error) return alert(error.message); setMilestones((v) => [...v, data]); setMilestoneTitle(""); setMilestoneDate(""); }
  async function toggleMilestone(item: any) { const statut = item.statut === "Terminé" ? "À faire" : "Terminé"; const { error } = await supabaseBrowser.from("internal_project_milestones").update({ statut }).eq("id", item.id); if (error) return alert(error.message); setMilestones((v) => v.map((m) => m.id === item.id ? { ...m, statut } : m)); }
  async function addResource(e: React.FormEvent) { e.preventDefault(); const { data, error } = await supabaseBrowser.from("internal_project_resources").insert({ project_id: project.id, nom: resourceName.trim(), url: resourceUrl.trim() }).select("*").single(); if (error) return alert(error.message); setResources((v) => [data, ...v]); setResourceName(""); setResourceUrl(""); }
  async function addUpdate(e: React.FormEvent) { e.preventDefault(); const { data, error } = await supabaseBrowser.from("internal_project_updates").insert({ project_id: project.id, contenu: updateText.trim(), type_update: updateType }).select("*, author:profiles!internal_project_updates_author_id_fkey(nom, full_name)").single(); if (error) return alert(error.message); setUpdates((v) => [data, ...v]); setUpdateText(""); }
  async function addMember(e: React.FormEvent) { e.preventDefault(); if (!memberId) return; const { data, error } = await supabaseBrowser.from("internal_project_members").upsert({ project_id: project.id, user_id: memberId, role_projet: memberRole }).select("*, profile:profiles!internal_project_members_user_id_fkey(id, nom, full_name, avatar_url)").single(); if (error) return alert(error.message); setMembers((v) => [data, ...v.filter((m) => m.user_id !== memberId)]); setMemberId(""); }

  const completeMilestones = milestones.filter((m) => m.statut === "Terminé").length;
  const taskDone = tasks.filter((t) => ["Terminé", "termine", "done"].includes(t.statut)).length;
  return <>
    <nav className="sticky top-0 z-20 mt-8 overflow-x-auto border-y border-zinc-800 bg-black/95 backdrop-blur"><div className="flex min-w-max">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`border-b-2 px-5 py-4 text-sm font-medium ${tab === item ? "border-yellow-400 text-white" : "border-transparent text-zinc-500 hover:text-zinc-300"}`}>{item}</button>)}</div></nav>

    {tab === "Vue d’ensemble" && <div className="mt-8 grid gap-6 xl:grid-cols-[1.4fr_0.6fr]">
      <div className="space-y-6"><Panel title="Objectif" value={project.objectif} /><div className="grid gap-6 md:grid-cols-2"><Panel title="Contexte" value={project.contexte} /><Panel title="Critères de réussite" value={project.criteres_reussite} /></div><Panel title="Dernières décisions" value={project.decisions} /></div>
      <aside className="space-y-6"><section className="rounded-3xl border border-zinc-800 bg-zinc-900 p-6"><Label>Avancement déclaré</Label><p className="mt-3 text-5xl font-bold">{project.progression || 0}%</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-black"><div className="h-full bg-yellow-400" style={{ width: `${project.progression || 0}%` }} /></div></section><Stat title="Jalons" value={`${completeMilestones}/${milestones.length}`} /><Stat title="Tâches terminées" value={`${taskDone}/${tasks.length}`} /><Stat title="Ressources" value={String(resources.length)} /></aside>
    </div>}

    {tab === "Cadrage" && <div className="mt-8 grid gap-6 xl:grid-cols-2"><Panel title="Contexte et base de travail" value={project.contexte} /><Panel title="Périmètre" value={project.perimetre} /><Panel title="Consignes permanentes" value={project.consignes} /><Panel title="Critères de réussite" value={project.criteres_reussite} /><Panel title="Risques et points de vigilance" value={project.risques} alert /><Panel title="Ressources générales" value={project.ressources} /></div>}

    {tab === "Exécution" && <div className="mt-8 grid gap-6 xl:grid-cols-[1fr_0.75fr]">
      <section className="rounded-3xl border border-zinc-800 bg-zinc-900 p-6"><div className="flex items-center justify-between"><div><Label>Production</Label><h2 className="mt-2 text-2xl font-bold">Tâches liées</h2></div><Link href={`/taches/nouveau?internal_project_id=${project.id}`} className="rounded-xl bg-white px-4 py-2 text-sm font-medium text-black">+ Tâche</Link></div><div className="mt-5 space-y-3">{!tasks.length ? <Empty text="Aucune tâche : ce projet peut rester une base de travail." /> : tasks.map((task) => <Link key={task.id} href={`/taches/${task.id}`} className="grid gap-2 rounded-2xl border border-zinc-800 bg-black p-4 hover:border-zinc-600 md:grid-cols-[1fr_120px]"><div><p className="font-medium">{task.titre}</p><p className="mt-1 text-xs text-zinc-500">{task.priorite || "Priorité non définie"} · {task.deadline || "Sans échéance"}</p></div><span className="text-sm text-zinc-400 md:text-right">{task.statut}</span></Link>)}</div></section>
      <div className="space-y-6"><section className="rounded-3xl border border-zinc-800 bg-zinc-900 p-6"><Label>Feuille de route</Label><h2 className="mt-2 text-2xl font-bold">Jalons</h2><form onSubmit={addMilestone} className="mt-5 grid gap-3"><input required value={milestoneTitle} onChange={(e) => setMilestoneTitle(e.target.value)} placeholder="Nouveau jalon" className="rounded-xl border border-zinc-800 bg-black p-3" /><div className="flex gap-3"><input type="date" value={milestoneDate} onChange={(e) => setMilestoneDate(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-zinc-800 bg-black p-3" /><button className="rounded-xl bg-white px-4 text-sm font-medium text-black">Ajouter</button></div></form><div className="mt-5 space-y-2">{milestones.map((item) => <button key={item.id} onClick={() => toggleMilestone(item)} className="flex w-full items-center gap-3 rounded-xl border border-zinc-800 bg-black p-3 text-left"><span className={`flex h-5 w-5 items-center justify-center rounded-full border ${item.statut === "Terminé" ? "border-emerald-400 bg-emerald-400 text-black" : "border-zinc-600"}`}>{item.statut === "Terminé" ? "✓" : ""}</span><span className={`flex-1 text-sm ${item.statut === "Terminé" ? "text-zinc-600 line-through" : ""}`}>{item.titre}</span><span className="text-xs text-zinc-600">{item.deadline || ""}</span></button>)}</div></section>
      <section className="rounded-3xl border border-zinc-800 bg-zinc-900 p-6"><Label>Gouvernance</Label><h2 className="mt-2 text-2xl font-bold">Équipe projet</h2><form onSubmit={addMember} className="mt-5 grid gap-3"><select value={memberId} onChange={(e) => setMemberId(e.target.value)} className="rounded-xl border border-zinc-800 bg-black p-3"><option value="">Ajouter un membre</option>{profiles.map((p) => <option key={p.id} value={p.id}>{p.nom || p.full_name || "Membre LMG"}</option>)}</select><div className="flex gap-3"><select value={memberRole} onChange={(e) => setMemberRole(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-zinc-800 bg-black p-3">{["Pilote","Contributeur","Validateur","Consulté"].map((r) => <option key={r}>{r}</option>)}</select><button className="rounded-xl bg-white px-4 text-sm font-medium text-black">Ajouter</button></div></form><div className="mt-5 space-y-2">{members.map((m) => <div key={m.user_id} className="flex items-center justify-between rounded-xl bg-black p-3"><span className="text-sm">{m.profile?.nom || m.profile?.full_name || "Membre LMG"}</span><span className="text-xs text-zinc-500">{m.role_projet}</span></div>)}</div></section></div>
    </div>}

    {tab === "Ressources" && <section className="mt-8 rounded-3xl border border-zinc-800 bg-zinc-900 p-6"><Label>Documentation</Label><h2 className="mt-2 text-2xl font-bold">Liens et ressources</h2><form onSubmit={addResource} className="mt-5 grid gap-3 md:grid-cols-[1fr_1.4fr_auto]"><input required value={resourceName} onChange={(e) => setResourceName(e.target.value)} placeholder="Nom de la ressource" className="rounded-xl border border-zinc-800 bg-black p-3" /><input required type="url" value={resourceUrl} onChange={(e) => setResourceUrl(e.target.value)} placeholder="https://..." className="rounded-xl border border-zinc-800 bg-black p-3" /><button className="rounded-xl bg-white px-5 font-medium text-black">Ajouter</button></form><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{!resources.length ? <Empty text="Aucune ressource structurée pour le moment." /> : resources.map((r) => <a key={r.id} href={r.url} target="_blank" rel="noreferrer" className="rounded-2xl border border-zinc-800 bg-black p-5 hover:border-yellow-400"><Label>{r.type_ressource}</Label><p className="mt-3 font-semibold">{r.nom}</p><p className="mt-2 truncate text-xs text-zinc-600">{r.url}</p></a>)}</div></section>}

    {tab === "Journal" && <section className="mt-8 grid gap-6 xl:grid-cols-[0.7fr_1.3fr]"><form onSubmit={addUpdate} className="h-fit rounded-3xl border border-zinc-800 bg-zinc-900 p-6"><Label>Nouvelle entrée</Label><h2 className="mt-2 text-2xl font-bold">Journal du projet</h2><select value={updateType} onChange={(e) => setUpdateType(e.target.value)} className="mt-5 w-full rounded-xl border border-zinc-800 bg-black p-3">{["Mise à jour","Décision","Alerte","Compte rendu"].map((v) => <option key={v}>{v}</option>)}</select><textarea required value={updateText} onChange={(e) => setUpdateText(e.target.value)} placeholder="Ce qui a changé, été décidé ou doit rester en mémoire..." className="mt-3 min-h-40 w-full rounded-xl border border-zinc-800 bg-black p-3" /><button className="mt-3 w-full rounded-xl bg-white p-3 font-medium text-black">Ajouter au journal</button></form><div className="space-y-4">{!updates.length ? <Empty text="Le journal est encore vide." /> : updates.map((u) => <article key={u.id} className="rounded-3xl border border-zinc-800 bg-zinc-900 p-6"><div className="flex items-center justify-between"><Label>{u.type_update}</Label><span className="text-xs text-zinc-600">{new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(u.created_at))}</span></div><p className="mt-4 whitespace-pre-wrap leading-7 text-zinc-300">{u.contenu}</p><p className="mt-4 text-xs text-zinc-600">{u.author?.nom || u.author?.full_name || "Équipe LMG"}</p></article>)}</div></section>}
  </>;
}

function Label({ children }: { children: React.ReactNode }) { return <p className="text-xs font-semibold uppercase tracking-[0.2em] text-yellow-400">{children}</p>; }
function Panel({ title, value, alert = false }: { title: string; value?: string | null; alert?: boolean }) { return <section className={`rounded-3xl border p-6 ${alert ? "border-red-500/20 bg-red-500/5" : "border-zinc-800 bg-zinc-900"}`}><h2 className="text-xl font-bold">{title}</h2><p className="mt-4 whitespace-pre-wrap leading-7 text-zinc-300">{value || "Aucune information renseignée."}</p></section>; }
function Stat({ title, value }: { title: string; value: string }) { return <div className="flex items-center justify-between rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><span className="text-zinc-400">{title}</span><span className="text-xl font-bold">{value}</span></div>; }
function Empty({ text }: { text: string }) { return <p className="rounded-2xl border border-dashed border-zinc-800 p-5 text-sm text-zinc-500">{text}</p>; }
