import {
  PERMISSIONS,
  type Permission,
} from "./permissions";

export const USER_ROLES = {
  PRESIDENT: "president",
  COFOUNDER: "cofounder",
  ARTISTIC_DIRECTOR: "artistic_director",
  ARTIST: "artist",
  TEAM: "team",
} as const;

export type UserRole =
  (typeof USER_ROLES)[keyof typeof USER_ROLES];

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<
  UserRole,
  readonly Permission[]
> = {
  president: ALL_PERMISSIONS,

  cofounder: ALL_PERMISSIONS,

  artistic_director: [
    PERMISSIONS.DASHBOARD_ARTISTIC_VIEW,

    PERMISSIONS.ARTISTS_VIEW,
    PERMISSIONS.ARTISTS_CREATE,
    PERMISSIONS.ARTISTS_UPDATE,
    PERMISSIONS.ARTISTS_ARCHIVE,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_UPDATE,
    PERMISSIONS.PROJECTS_ARCHIVE,

    PERMISSIONS.RELEASES_VIEW,
    PERMISSIONS.RELEASES_CREATE,
    PERMISSIONS.RELEASES_UPDATE,

    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_CREATE,
    PERMISSIONS.MEDIA_UPDATE,
    PERMISSIONS.MEDIA_DELETE,

    PERMISSIONS.MARKETING_VIEW,
    PERMISSIONS.MARKETING_CREATE,
    PERMISSIONS.MARKETING_UPDATE,

    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_CREATE,
    PERMISSIONS.CRM_UPDATE,

    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CALENDAR_CREATE,
    PERMISSIONS.CALENDAR_UPDATE,
    PERMISSIONS.CALENDAR_DELETE,

    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.TASKS_ASSIGN,

    PERMISSIONS.DISCUSSIONS_VIEW,
    PERMISSIONS.DISCUSSIONS_CREATE,

    PERMISSIONS.TEAM_VIEW,
  ],

  artist: [
    PERMISSIONS.ARTISTS_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.RELEASES_VIEW,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.DISCUSSIONS_VIEW,
    PERMISSIONS.DISCUSSIONS_CREATE,
  ],

  team: [
    PERMISSIONS.ARTISTS_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.RELEASES_VIEW,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.DISCUSSIONS_VIEW,
    PERMISSIONS.DISCUSSIONS_CREATE,
  ],
};