import {
  PERMISSIONS,
  type Permission,
} from "./permissions";
import { ROLES } from "@/lib/roles";

export const USER_ROLES = {
  SUPER_ADMIN: ROLES.SUPER_ADMIN,
  ADMIN: ROLES.ADMIN,
  MANAGER: ROLES.MANAGER,
  ARTISTIC_DIRECTOR: ROLES.ARTISTIC_DIRECTOR,
  ARTISTE: ROLES.ARTISTE,
  PRESTATAIRE: ROLES.PRESTATAIRE,
} as const;

export type UserRole =
  (typeof USER_ROLES)[keyof typeof USER_ROLES];

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<
  UserRole,
  readonly Permission[]
> = {
  super_admin: ALL_PERMISSIONS,

  admin: ALL_PERMISSIONS,

  manager: [
    PERMISSIONS.DASHBOARD_ARTISTIC_VIEW,
    PERMISSIONS.ARTISTS_VIEW,
    PERMISSIONS.ARTISTS_UPDATE,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_UPDATE,
    PERMISSIONS.RELEASES_VIEW,
    PERMISSIONS.RELEASES_CREATE,
    PERMISSIONS.RELEASES_UPDATE,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_CREATE,
    PERMISSIONS.MEDIA_UPDATE,
    PERMISSIONS.MARKETING_VIEW,
    PERMISSIONS.MARKETING_CREATE,
    PERMISSIONS.MARKETING_UPDATE,
    PERMISSIONS.BOOKINGS_VIEW,
    PERMISSIONS.BOOKINGS_CREATE,
    PERMISSIONS.BOOKINGS_UPDATE,
    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_CREATE,
    PERMISSIONS.CRM_UPDATE,
    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CALENDAR_CREATE,
    PERMISSIONS.CALENDAR_UPDATE,
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.TASKS_ASSIGN,
    PERMISSIONS.DISCUSSIONS_VIEW,
    PERMISSIONS.DISCUSSIONS_CREATE,
    PERMISSIONS.CONTRACTS_VIEW,
    PERMISSIONS.ROYALTIES_VIEW,
  ],

  artistic_director: [
    PERMISSIONS.DASHBOARD_ARTISTIC_VIEW,

    PERMISSIONS.ARTISTS_VIEW,
    PERMISSIONS.ARTISTS_CREATE,
    PERMISSIONS.ARTISTS_UPDATE,
    PERMISSIONS.ARTISTS_ARCHIVE,

    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_UPDATE,
    PERMISSIONS.PROJECTS_ARCHIVE,

    PERMISSIONS.RELEASES_VIEW,
    PERMISSIONS.RELEASES_CREATE,
    PERMISSIONS.RELEASES_UPDATE,

    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_CREATE,
    PERMISSIONS.MEDIA_UPDATE,
    PERMISSIONS.MEDIA_DELETE,

    PERMISSIONS.MARKETING_VIEW,
    PERMISSIONS.MARKETING_CREATE,
    PERMISSIONS.MARKETING_UPDATE,

    PERMISSIONS.CRM_VIEW,
    PERMISSIONS.CRM_CREATE,
    PERMISSIONS.CRM_UPDATE,

    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CALENDAR_CREATE,
    PERMISSIONS.CALENDAR_UPDATE,
    PERMISSIONS.CALENDAR_DELETE,

    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.TASKS_ASSIGN,

    PERMISSIONS.DISCUSSIONS_VIEW,
    PERMISSIONS.DISCUSSIONS_CREATE,

    PERMISSIONS.TEAM_VIEW,
  ],

  artiste: [
    PERMISSIONS.ARTISTS_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.RELEASES_VIEW,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.DISCUSSIONS_VIEW,
    PERMISSIONS.DISCUSSIONS_CREATE,
    PERMISSIONS.CONTRACTS_VIEW,
    PERMISSIONS.ROYALTIES_VIEW,
  ],

  prestataire: [
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.DISCUSSIONS_VIEW,
    PERMISSIONS.DISCUSSIONS_CREATE,
  ],
};
